export const environment = {
  chekLoginUrl: 'http://localhost:8080/linkshortener-web/user/chekLogin',
  signInUrl: 'http://localhost:8080/linkshortener-web/user/signIn',
  signOutUrl: 'http://localhost:8080/linkshortener-web/user/signOut',
  createUserUrl: 'http://localhost:8080/linkshortener-web/user',
  getShortUrl: 'http://localhost:8080/linkshortener-web/link/shortLink',
  createDeleteLink: 'http://localhost:8080/linkshortener-web/link/',
  updateLink: 'http://localhost:8080/linkshortener-web/link',
  getAllLink: 'http://localhost:8080/linkshortener-web/link/all',
  userLinks : 'http://localhost:8080/linkshortener-web/link/userLinks',
  getLinkByShotrUrl: 'http://localhost:8080/linkshortener-web/link/',
  getLinksByTag: 'http://localhost:8080/linkshortener-web/tag/links/',
  createTag: 'http://localhost:8080/linkshortener-web/tag',
  deleteTag: 'http://localhost:8080/linkshortener-web/tag/',
};
